os:
  - linux
  #- osx

language: c

#python: # We don't actually use the Travis Python, but this keeps it organized.
  #- "2.7"
  #- "3.4"
  #- "3.5"
  #- "3.6"

sudo: required

install:

  # Install requirements. Taken from yoda's post http://forum.abinit.org/viewtopic.php?f=2&t=1391
  #- sudo apt-get update
  - sudo apt-get -y install gcc g++ gfortran
  - sudo apt-get -y install patch
  - sudo apt-get -y install libnetcdf-dev
  - sudo apt-get -y install fftw3 libfftw3-single3 libfftw3-dev
  - sudo apt-get -y install libatlas-base-dev libatlas3gf-base
  - sudo apt-get -y install liblapack3gf liblapack-dev
  - sudo apt-get -y install libblas3gf libblas-dev
  - sudo apt-get -y install openmpi-bin openmpi-common libopenmpi-dev

  - ./config/scripts/makemake 

  - ./configure --help
  - ./configure --prefix="/usr/local" FCFLAGS="-g -O2 -ffree-line-length-none" --with-mpi-prefix="/usr" --enable-mpi-io="yes"
        --with-netcdf-incs="-I/usr/include" --with-netcdf-libs="-L/usr/lib64 -lnetcdf -lnetcdff"
        --with-fft-flavor="fftw3" --with-fft-incs="-I/usr/include/" --with-fft-libs="-L/usr/lib64 -lfftw3"
        --with-linalg-flavor="atlas" --with-linalg-libs="-L/usr/lib64 -llapack -lf77blas -lcblas -latlas"
        --with-dft-flavor="atompaw+libxc+wannier90" --enable-gw-dpc="yes"

  - make -j4
  - make check
  - sudo make install

# command to run tests
script: make check && tests/runtests.py fast v1 v2 -n2

branches:
  only:
    - travis
    - master
    - develop

notifications:
  email:
    recipients:
      - gmatteo@gmail.com
    on_success: change
    on_failure: always
