os:
  - linux
  #- osx

language: c

sudo: required

install:

  # Install requirements. Taken from yoda's post http://forum.abinit.org/viewtopic.php?f=2&t=1391
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
  #     brew update;
  #     brew install gcc;
  #  fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
  #     sudo apt-get install liblapack-dev libblas-dev;
  #  fi
  #- sudo apt-get update
  - sudo apt-get -y install gcc gfortran g++
  - sudo apt-get -y install patch
  # blas/lapack
  - sudo apt-get -y install libatlas-base-dev libatlas3gf-base
  - sudo apt-get -y install liblapack3gf liblapack-dev
  - sudo apt-get -y install libblas3gf libblas-dev
  # fftw3 (ubuntu version on travis does not provide single precision version (required by Abinit)
  #- sudo apt-get -y install fftw3 libfftw3-single3 libfftw3-dev
  # netcdf
  - sudo apt-get -y install libnetcdf-dev
  # openmpi
  - sudo apt-get -y install openmpi-bin openmpi-common libopenmpi-dev

  - ./config/scripts/makemake 

  - ./configure --help
  - ./configure --prefix="/usr/local" FCFLAGS="-g -O2 -ffree-line-length-none" --with-mpi-prefix="/usr" --enable-mpi-io="yes"
        --with-netcdf-incs="-I/usr/include" --with-netcdf-libs="-L/usr/lib64 -lnetcdf -lnetcdff"
        --with-linalg-flavor="atlas" --with-linalg-libs="-L/usr/lib64 -llapack -lf77blas -lcblas -latlas"
        --with-dft-flavor="atompaw+libxc+wannier90" --enable-gw-dpc="yes"
        #--with-fft-flavor="fftw3" --with-fft-incs="-I/usr/include/" --with-fft-libs="-L/usr/lib64 -lfftw3"

  - make -j4
  - make check
  - sudo make install

# command to run tests
script: make check && tests/runtests.py fast v1 v2 -n2

branches:
  only:
    - travis
    - master
    - develop

notifications:
  email:
    recipients:
      - gmatteo@gmail.com
    on_success: change
    on_failure: always
